### PR TITLE
Changes title a little :)

### PR DESCRIPTION
**Pull request by KaffinPX**
Old title was looking weird so i changed it to a better title

### CODE REVIEW

**Review by extremeheat — APPROVED** [review]

**Comment by u9g** [comment]
its fine the way it is imo

**Comment by KaffinPX** [comment]
Thanks

**Comment by extremeheat** [comment]
Yeah, I think it’s fine as is but don’t really have a preference on it

**Comment by KaffinPX** [comment]
Why its not merged???

**Pull request merged**
