### PR TITLE
Increased badge drip

### PR DESCRIPTION
**Pull request by DJStompZone**
<details><summary>Added dynamic content and restyled for improved swagger</summary></details>

### CODE REVIEW

**Comment by extremeheat** [comment]
The bigger discord badge was added in https://github.com/PrismarineJS/mineflayer/pull/2461 after discussion on discord in #contribute. Reverting it to be consistent with the other non-mineflayer prismarine- repositories will probably make sense once mineflayer can support bedrock-protocol.

**Comment by DJStompZone** [comment]
I'd take that trade any day

**Comment by DJStompZone** [comment]
Still struggling to see the issue with this PR


A)
[NPM version](http://npmjs.com/package/bedrock-protocol)
[Build Status](https://github.com/PrismarineJS/bedrock-protocol/actions?query=workflow%3A%22CI%22)
[Try it on gitpod](https://gitpod.io/#https://github.com/PrismarineJS/bedrock-protocol)

[Official Discord](https://discord.gg/GsEFRM8)

<hr>

B)

<p align="left">
 <a href="http://npmjs.com/package/bedrock-protocol">Bedrock-Protocol on NPM</a>
 <a href="https://github.com/PrismarineJS/bedrock-protocol/actions?query=workflow%3A%22CI%22">
  CI workflow status</a><br>
 Most recent commit to this repository<br>
 <a href="https://gitpod.io/#https://github.com/PrismarineJS/bedrock-protocol">Try bedrock-protocol on Gitpod.io</a><br><a href="https://discord.gg/GsEFRM8"> <a href="https://discord.gg/GsEFRM8">Official PrismarineJS Discord server</a><br>
 </p>

**Comment by extremeheat** [comment]
If we change it here this needs to be propagated to the other prismarine projects and the template to be consistent

**Comment by rom1504** [comment]
I think the current is better

**Pull request closed without merging**
