### PR TITLE
Allow catching relay errors

### PR DESCRIPTION
**Pull request by GameParrot**

### CODE REVIEW

**Comment by extremeheat** [comment]
This is not good as it will crash the program instead of disconnecting a user on a users' session going bad.

**Comment by rom1504** [comment]
failing

**Comment by GameParrot** [comment]
> This is not good as it will crash the program instead of disconnecting a user on a users' session going bad.

It crashed the program before even if the error wasn’t handled. Maybe add relay.on(‘error’) and pass the error and player to it.

**Comment by extremeheat** [comment]
As the primary purpose of the Relay proxy here is debugging, it is intentional that errors from the player (which we do not expect) will crash the proxy, but errors from a server affecting a specific client will lead to just their disconnection.

**Comment by extremeheat** [comment]
What you're doing in this PR is removing error handling and leaving clients hanging (which will ultimately timeout without knowing why). If we could disconnect the player on player errors, we would, however we can't do that because it's the player side itself with the error. I think kicking the client and telling them why so they can reconnect and logging the output is better from a default functionality standpoint. Aside from your edge case, do you see much other benefit for general cases here?

**Comment by GameParrot** [comment]
maybe add an option to the relay to disable error handling and allow catching errors, disabled by default

**Comment by extremeheat** [comment]
Same comment as above
> Aside from your edge case, do you see much other benefit for general cases here?

We already are adding a feature to handle errors in #435. Adding a feature to the API is a commitment that we keep it going without breaking functionality. If it’s only something that fixes a problem in one situation it may make more sense to implement a custom Relay to handle those behaviors as opposed to hacking around the error handling, which seems like messy API to me.

**Pull request closed without merging**
