### PR TITLE
Ping Response: Skip 2 bytes for message size

### LINKED ISSUE #274: Ping function (server advertisement) includes packet size in string header
While testing 1.19.30, I noticed some odd behavior with the advertisement feature. Given the following advertisement:

```
0000   02 00 00 00 45 00 00 88 80 f8 00 00 80 11 00 00   ....E...........
0010   7f 00 00 01 7f 00 00 01 4a be cf af 00 74 57 26   ........J....tW&
0020   1c 00 00 00 00 a4 02 3e 65 ca a7 6a 06 9f d4 1e   .......>e..j....
0030   87 00 ff ff 00 fe fe fe fe fd fd fd fd 12 34 56   ..............4V
0040   78 00 49 4d 43 50 45 3b 42 65 64 72 6f 63 6b 20   x.IMCPE;Bedrock 
0050   50 72 6f 74 6f 63 6f 6c 20 53 65 72 76 65 72 3b   Protocol Server;
0060   35 35 33 3b 31 2e 31 39 2e 33 30 3b 30 3b 33 3b   553;1.19.30;0;3;
0070   30 3b 62 65 64 72 6f 63 6b 2d 70 72 6f 74 6f 63   0;bedrock-protoc
0080   6f 6c 3b 43 72 65 61 74 69 76 65 3b               ol;Creative;
```

running `bedrock-protocol.ping` returns the following object:

```
ServerAdvertisement {
  motd: 'Bedrock Protocol Server',
  levelName: 'bedrock-protocol',
  playersOnline: '0',
  playersMax: '3',
  gamemode: 'Creative',
  serverId: '0',
  protocol: '553',
  version: '1.19.30',
  header: '\x00IMCPE'
}
```

The `header` field has some hex in it, more easily seen if we hex-dump the advertisement before parsing: `<Buffer 00 49 4d 43 50 45 3b 42 65 64 72 6f 63 6b 20 50 72 6f 74 6f 63 6f 6c 20 53 65 72 76 65 72 3b 35 35 33 3b 31 2e 31 39 2e 33 30 3b 30 3b 33 3b 30 3b 62 ... 25 more bytes>`

`00 49` is the Raknet packet string length packet, but is being included in the high-level advertisement function.

### PR DESCRIPTION
**Pull request by stevarino**
Unsure if this is the right way as I can find no documentation on this, but should fix https://github.com/PrismarineJS/bedrock-protocol/issues/274

### CODE REVIEW

**Comment by extremeheat** [comment]
This is not correct fix, as server advertisement would also be incorrect (so we should fix inside server/advertisement). I believe the mechanics of this may have changed from a prior version

**Comment by stevarino** [comment]
This function is upstream of server/advertisement, correct? Further server/advertisement receives a utf-8 string so we could not do a two-byte adjustment (easily) on that input. 

The output of server/advertisement is where I discovered this issue, but we typically don't use the field this affects (`header`):

```
ServerAdvertisement {
  motd: 'BlahBlah',
  levelName: 'My World',
  playersOnline: '1',
  playersMax: '5',
  gamemode: 'Creative',
  serverId: '13124841751394787494',
  protocol: '554',
  version: '1.19.40.20',
  header: '\x00VMCPE'  # should be 'MCPE'
}
```

**Comment by stevarino** [comment]
I guess the "correctest" fix would be to treat `pong` return value as a binary non-null-terminated string with two-byte length prepended and parse it accordingly, but the end result would be the same.

**Comment by extremeheat** [comment]
Yeah, I don't think this is a problem (minecraft identifies the server with or without a length header) but it's possible this is something that should be handled at RakNet level. Since RakNet unconnected pong data is not necessarily a length-prefixed string (could be an integer or some other binary structure) we may want to return a Buffer that can be skipped 2 bytes inside bedrock-protocol for the actual string. 

In RakNet, the pong data is just written as a non-length prefixed string
https://github.dev/extremeheat/fb-raknet/blob/9af9fb2d74c56c87d54071d7aac93cf0c28b110a/Source/RakPeer.cpp#L2285-L2286

**Comment by rom1504** [comment]
do you plan to finish this ?

**Comment by rom1504** [comment]
old

**Pull request closed without merging**
