### PR TITLE
add flow and deviceType to relay

### PR DESCRIPTION
**Pull request by GameParrot**
for when authTitle is changed

### CODE REVIEW

**Comment by rom1504** [comment]
can you add more details on usage of this?

**Comment by GameParrot** [comment]
> can you add more details on usage of this?

Allows for properly logging in with a different auth title
Without this change it isnt possible to log in with an auth title other than nintendo

**Review by extremeheat — COMMENTED** [review]
This should be documented in the types if this is passed through

**Comment by rom1504** [comment]
@GameParrot any updates?

**Review by extremeheat — APPROVED** [review]

**Comment by extremeheat** [comment]
I fixed it, in future PRs please remember to update doc for what is changed

**Pull request merged**
