### PR TITLE
Release 3.29.1

### PR DESCRIPTION
**Pull request by Nyrok**
Bad packet: Error processing LoginPacket: Required property "CompatibleWithClientSideChunkGen" of class pocketmine\network\mcpe\protocol\types\login\ClientData is missing in JSON data

### CODE REVIEW

**Comment by extremeheat** [comment]
This was already fixed in #420. It's just missing a release. Feel free to open a release PR.

**Comment by Nyrok** [comment]
> This was already fixed in #420. It's just missing a release. Feel free to open a release PR. 

Alright.

**Comment by extremeheat** [comment]
FYI, the history.md file should only include things relevant to API users. I've updated the PR.

**Comment by Nyrok** [comment]
> FYI, the history.md file should only include things relevant to API users. I've updated the PR.

Understood.

**Review by extremeheat — APPROVED** [review]

**Pull request merged**
