### PR TITLE
Start work on multi-version support, test cleanup

### PR DESCRIPTION
**Pull request by extremeheat**
Refactor some logic to allow for multi-version support, also removed some test code, I think some of the data can be moved to mcdata once this is stable

Not linting here to keep the diffs small, will do that in the next pr

### CODE REVIEW

**Review by KaffinPX — COMMENTED** [review]
is it working

**Comment by extremeheat** [comment]
> is it working

It works, but it's not usable yet. Should be usable soon

**Comment by rom1504** [comment]
Ready for review ?

**Comment by rom1504** [comment]
Looks kind of ok

Main question : why don't you generate the compiled js at run time like we do for mcpc ?

**Comment by extremeheat** [comment]
It's primarily for debugging, evaling at runtime doesn't give a useful stack trace

**Comment by extremeheat** [comment]
Should be ready for review

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
