### PR TITLE
fix: type definition errors found related to ServerAdvertisements.

### PR DESCRIPTION
**Pull request by JammSpread**
Fixes the definition of where the online/max player counts are.

(Sorry for another type definition fix. 🌵)

### CODE REVIEW

**Comment by JammSpread** [comment]
Although this may conflict with #35.

**Comment by extremeheat** [comment]
Can you also add `advertisementFn` to the server definitions? Seems to be missing also

**Comment by JammSpread** [comment]
Oh okay, I'll try to look into it.

**Comment by JammSpread** [comment]
There seems to be some parity issues between the API docs, the type definitions, and the source code.
Should I attempt to try and fix them in this PR?

**Comment by extremeheat** [comment]
Sure, go ahead

**Review by extremeheat — APPROVED** [review]

**Comment by extremeheat** [comment]
Thanks

**Pull request merged**
