### PR TITLE
Vanilla server tests, client offline mode

### PR DESCRIPTION
**Pull request by extremeheat**
WIP

Start work on tests against vanilla server, should be runnable on CI in #47

### CODE REVIEW

**Comment by rom1504** [comment]
can you rebase on master ?

**Comment by rom1504** [comment]
this test file seems to be asking for auth
how can this work in CI ?

**Comment by extremeheat** [comment]
Haven't implemented offline mode yet, but for online mode we can make a ms account for testing, auth locally and then put the ms auth cache file in as a secret. Then on CI it would write the JSON somewhere then auth from it.

in [authFlow.js](https://github.com/prismarinejs/node-minecraft-protocol/blob/master/src/client/authFlow.js#L52) only the msa-cache.json file with the access+refresh token is needed, then the other tokens can be generated from web requests

**Comment by rom1504** [comment]
This is pretty cool

The server downloading part could have a good place in node-minecraft-wrap (but ok to keep it there for now of course)

**Comment by extremeheat** [comment]
ok, I think it should be mergable in its current state, can add internal tests/server offline in another PR

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
