### PR TITLE
Add Get-AppxPackage command to FAQ.md

### PR DESCRIPTION
**Pull request by stevarino**
Needed to locate odd Minecraft versions, as discussed in discord.

### CODE REVIEW

**Comment by extremeheat** [comment]
I just checked, the identifier for betas should be `Microsoft.MinecraftWindowsBeta`. A simple "on minecraft win10 beta versions, swap MinecraftUWP for MinecraftWindowsBeta" or alternative command I think should suffice.

**Comment by stevarino** [comment]
Interesting. So the preview builds using MCMrARM is also listed under `Microsoft.MinecraftWindowsBeta` and installing multiple versions only lists the latest one through Get-AppxPackage. It's likely hijacking the standard beta feature.

Also, running `CheckNetIsolation LoopbackExempt -a -n="Microsoft.MinecraftWindowsBeta"` and `CheckNetIsolation LoopbackExempt -a -n="$_.PackageFullName"` results in two entries listed under `CheckNetIsolation LoopbackExempt -s` differentiated by just a rather opaque "SID" field.

So my thinking is the more detailed instructions could help someone if they get stuck or the command works differently between name's and fullname's, but I don't really know powershell and I don't really care to know powershell so willing to just got with whatever you think is needed. Also this is a pretty minor issue. 

What if we just add all three cases: default command, beta command, "find the binary" command? Extra troubleshooting steps in a markdown never hurt anybody.

**Comment by extremeheat** [comment]
Yeah sure. We should just keep the FAQ as simple as possible to cover issues broadly, so having a simple command to paste and run for X situation is good and understandable for users. Should not need to know powershell or decipher a complex command.

**Comment by stevarino** [comment]
Also available would be the potentially overkill command:

```
Get-AppxPackage -AllUsers | Where Name -Match ".*Minecraft.*" | Foreach -Process {CheckNetIsolation LoopbackExempt -a -n="$_.PackageFullName"}
```

**Comment by stevarino** [comment]
What a weird set of commands. I now have 5 Loopback exceptions for 2 minecraft versions. The SID's appear to repeat from earlier deleted ones, indicating they are external references and not just UUID's. So it is doing something that makes sense, just not to me.

Anyway, I put forth a 3 step debugging process in this PR. I agree with you about keeping things simple but happy to yield whichever way you think is preferable. :-)

**Comment by extremeheat** [comment]
Thanks, will assume this is working.

**Review by extremeheat — APPROVED** [review]

**Pull request merged**
