### PR TITLE
fix raknet-node ping timeout in CI.

### PR DESCRIPTION
**Pull request by b23r0**

### CODE REVIEW

**Comment by extremeheat** [comment]
Why is the ping failing?

**Comment by b23r0** [comment]
> Why is the ping failing?

I'm doing some testing and will fix this soon.

**Comment by b23r0** [comment]
> Why is the ping failing?

Since the client's backend library and the server's backend library used by ping are not the same library, there may be some compatibility issues here. I am looking for the problem and fixing it.

**Comment by b23r0** [comment]
Unknown reason ping timed out in CI environment. The problem cannot be reproduced after many local tests, it is recommended to skip ping in CI.

**Pull request closed without merging**
